export default {
  CHANGE_MENU_STATE: 'CHANGE_MENU_STATE',
  CHANGING_EMAIL_FIELD: 'CHANGING_EMAIL_FIELD',
  TOGGLE_DROPDOWN: 'TOGGLE_DROPDOWN',
  SELECT_TAB: 'SELECT_TAB',
  TOGGLE_ACTIVE_USER: 'TOGGLE_ACTIVE_USER',
  GET_NEXT_USER: 'GET_NEXT_USER',
  GET_PREV_USER: 'GET_PREV_USER'
};
